version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    restart: always