version: '3.8'

services:
  backend:
    build:
      context: ./Backend  # Path to backend Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env  # Load environment variables from .env file
    depends_on:
      - redis
      - mongo
    volumes:
      - ./Backend:/app  # Mount local code into container for development
      - /app/node_modules  # Avoid overwriting node_modules
    restart: always

  frontend:
    build:
      context: ./Frontend  # Path to frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app  # Mount local code into container for development
      - /app/node_modules  # Avoid overwriting node_modules
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7.0
    container_name: redisdb
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongo_data:
  redis_data:
