version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    depends_on:
      - redis
      - mongo
    volumes:
      - ./Backend:/app
      - /app/node_modules
    restart: always